version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
      timezone: "America/New_York"
    target-branch: "beta"
    assignees: ["ZeliardM"]
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
      timezone: "America/New_York"
    target-branch: "beta"
    assignees: ["ZeliardM"]
    versioning-strategy: "increase"
    commit-message:
      prefix: "pip"
      prefix-development: "pip-dev"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
      timezone: "America/New_York"
    target-branch: "beta"
    assignees: ["ZeliardM"]
    commit-message:
      prefix: "ci"
      include: "scope"