docs:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

branding:
  - changed-files:
    - any-glob-to-any-file: branding/**

enhancement:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
    - any-glob-to-any-file: 'config.schema.json'
  - head-branch: '^feature/.*'
  - head-branch: '^feat/.*'
  - title: '^feat.*'

dependency:
  - changed-files:
    - any-glob-to-any-file: 'package.json'
    - any-glob-to-any-file: 'package-lock.json'
    - any-glob-to-any-file: 'requirements.txt'

workflow:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

fix:
  - head-branch: '^fix/.*'
  - head-branch: '^hotfix/.*'
  - head-branch: '.*/fix-.*'
  - title: '^fix.*'
  - title: '^Fix.*'

bug:
  - head-branch: '^bug/.*'
  - head-branch: '.*/bug-.*'
  - title: '.*[Bb]ug.*'

breaking-change:
  - head-branch: '.*breaking.*'
  - title: '.*BREAKING CHANGE.*'
  - title: '.*breaking change.*'
  - title: '.*BREAKING.*'
  - title: '.*breaking.*'

beta:
  - base-branch: 'beta'
latest:
  - base-branch: 'latest'
