---
name: Labeler

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: homebridge/.github/.github/workflows/labeler.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
